# Generated by Django 3.1.2 on 2020-11-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='nome',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
