# Generated by Django 3.1.2 on 2020-12-03 23:45

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_auto_20201122_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='quantidade',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='data_cadastro',
            field=models.DateField(default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AlterField(
            model_name='pet',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
