# Generated by Django 3.1.2 on 2020-11-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_pet_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='cep',
            field=models.CharField(default=23982, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='cidade',
            field=models.CharField(default='São Gonçalo', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='descricao',
            field=models.TextField(default='Um animal legal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='estado',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins'), ('DF', 'Distrito Federal')], default='Rio de Janeiro', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='grupo',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
