# Generated by Django 3.1.2 on 2020-12-05 20:06

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_auto_20201203_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='data_cadastro',
            field=models.DateField(blank=True, default=django.utils.datetime_safe.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='dislikes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='disponivel',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='imagem',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='likes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='link_facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='link_instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
