# Generated by Django 3.1.2 on 2020-11-02 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_auto_20201102_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='grupo',
            new_name='raca',
        ),
    ]
