# Generated by Django 3.1.2 on 2020-12-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0006_auto_20201205_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
