# Generated by Django 3.1.2 on 2020-11-02 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0006_auto_20201102_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='data_cadastro',
            field=models.DateField(default=datetime.date(2020, 11, 2)),
            preserve_default=False,
        ),
    ]
