# Generated by Django 3.1.2 on 2020-11-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0007_pet_data_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pet',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
